var wms_layers = [];

var lyr_ReliefVisibleentre18000000et125000_0 = new ol.layer.Tile({
                            source: new ol.source.TileWMS(({
                              url: "http://georef.application.i2/cartes/mapserv",
    attributions: ' ',
                              params: {
                                "LAYERS": "relief",
                                "TILED": "true",
                                "VERSION": "1.3.0"},
                            })),
                            title: "Relief - Visible entre 1/8 000 000 et 1/25 000",
                            opacity: 1.000000,
                            
                            
                          });
              wms_layers.push([lyr_ReliefVisibleentre18000000et125000_0, 0]);
var format_ZE_OCCITANIE_1 = new ol.format.GeoJSON();
var features_ZE_OCCITANIE_1 = format_ZE_OCCITANIE_1.readFeatures(json_ZE_OCCITANIE_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_ZE_OCCITANIE_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_ZE_OCCITANIE_1.addFeatures(features_ZE_OCCITANIE_1);
var lyr_ZE_OCCITANIE_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_ZE_OCCITANIE_1, 
                style: style_ZE_OCCITANIE_1,
                interactive: true,
                title: '<img src="styles/legend/ZE_OCCITANIE_1.png" /> ZE_OCCITANIE'
            });
var format_contour_ZE_Occitanie_2 = new ol.format.GeoJSON();
var features_contour_ZE_Occitanie_2 = format_contour_ZE_Occitanie_2.readFeatures(json_contour_ZE_Occitanie_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_contour_ZE_Occitanie_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_contour_ZE_Occitanie_2.addFeatures(features_contour_ZE_Occitanie_2);
var lyr_contour_ZE_Occitanie_2 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_contour_ZE_Occitanie_2, 
                style: style_contour_ZE_Occitanie_2,
                interactive: true,
                title: '<img src="styles/legend/contour_ZE_Occitanie_2.png" /> contour_ZE_Occitanie'
            });
var format_evolution_pop_ZE_3 = new ol.format.GeoJSON();
var features_evolution_pop_ZE_3 = format_evolution_pop_ZE_3.readFeatures(json_evolution_pop_ZE_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_evolution_pop_ZE_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_evolution_pop_ZE_3.addFeatures(features_evolution_pop_ZE_3);
var lyr_evolution_pop_ZE_3 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_evolution_pop_ZE_3, 
                style: style_evolution_pop_ZE_3,
                interactive: true,
                title: 'evolution_pop_ZE'
            });

lyr_ReliefVisibleentre18000000et125000_0.setVisible(true);lyr_ZE_OCCITANIE_1.setVisible(true);lyr_contour_ZE_Occitanie_2.setVisible(true);lyr_evolution_pop_ZE_3.setVisible(true);
var layersList = [lyr_ReliefVisibleentre18000000et125000_0,lyr_ZE_OCCITANIE_1,lyr_contour_ZE_Occitanie_2,lyr_evolution_pop_ZE_3];
lyr_ZE_OCCITANIE_1.set('fieldAliases', {'ID': 'ID', 'NOM_COM': 'NOM_COM', 'NOM_COM_M': 'NOM_COM_M', 'INSEE_COM': 'INSEE_COM', 'STATUT': 'STATUT', 'POPULATION': 'POPULATION', 'INSEE_CAN': 'INSEE_CAN', 'INSEE_ARR': 'INSEE_ARR', 'INSEE_DEP': 'INSEE_DEP', 'INSEE_REG': 'INSEE_REG', 'CODE_EPCI': 'CODE_EPCI', 'LIBGEO': 'LIBGEO', 'ZE2020': 'ZE2020', 'LIBZE2020': 'LIBZE2020', 'ZE2020_PAR': 'ZE2020_PAR', 'DEP': 'DEP', 'REG': 'REG', 'BE2021': 'BE2021', 'LIBBE2021': 'LIBBE2021', 'codeZE20': 'codeZE20', 'pop2019': 'pop2019', 'pop_partRegion': 'pop_partRegion', 'evol_pop': 'evol_pop', 'pop_15ansplus': 'pop_15ansplus', 'niveau_vie_median': 'niveau_vie_median', 'niveau_vie_decile1': 'niveau_vie_decile1', 'niveau_vie_decile9': 'niveau_vie_decile9', 'taux_pauvrete': 'taux_pauvrete', 'taux_pauvrete_moins30': 'taux_pauvrete_moins30', 'diplôme_pas_peu': 'diplôme_pas_peu', 'diplôme_BEPC_brevet': 'diplôme_BEPC_brevet', 'diplôme_CAP_BEP': 'diplôme_CAP_BEP', 'diplôme_BAC': 'diplôme_BAC', 'diplôme_EnSup': 'diplôme_EnSup', 'part_0diplomes_nonScolarise': 'part_0diplomes_nonScolarise', 'Nb_non_scolarise': 'Nb_non_scolarise', 'taux_activite_15a24ans': 'taux_activite_15a24ans', 'taux_activite_ensemble': 'taux_activite_ensemble', 'taux_chomage': 'taux_chomage', 'Etab_construction': 'Etab_construction', 'Etab_TouSecteur': 'Etab_TouSecteur', 'creation_ent_TouSecteur': 'creation_ent_TouSecteur', 'part_creation_construction': 'part_creation_construction', 'etab_employeurs': 'etab_employeurs', 'part_effectif_construction': 'part_effectif_construction', 'pas_transport': 'pas_transport', 'marchePied': 'marchePied', 'velo': 'velo', 'deuxroues': 'deuxroues', 'voiture': 'voiture', 'transportsCommun': 'transportsCommun', 'taux_independance': 'taux_independance', 'indicateur_jeunesse': 'indicateur_jeunesse', 'nb_emploi_LT': 'nb_emploi_LT', 'taux_activite_25a54ans': 'taux_activite_25a54ans', 'taux_activite_55a64ans': 'taux_activite_55a64ans', 'part_appartement': 'part_appartement', 'logements': 'logements', 'part_RP': 'part_RP', 'part_RS': 'part_RS', 'part_LV': 'part_LV', 'part_proprio_RS': 'part_proprio_RS', 'part_maisons': 'part_maisons', 'part_RP_av46': 'part_RP_av46', 'AUT_Logt2020': 'AUT_Logt2020', 'COM_Logt2020': 'COM_Logt2020', 'COM_part_LogtIndiv2020': 'COM_part_LogtIndiv2020', 'AUT_part_LogtIndiv2020': 'AUT_part_LogtIndiv2020', 'AUT_part_LogtColl2020': 'AUT_part_LogtColl2020', 'COM_part_LogtColl2020': 'COM_part_LogtColl2020', 'OEE_Cons_Durable': 'OEE_Cons_Durable', 'OEE_Cons_NonDurable': 'OEE_Cons_NonDurable', 'OEE_Cons_Total': 'OEE_Cons_Total', 'OEE_Ens_Durable': 'OEE_Ens_Durable', 'OEE_Ens_NonDurable': 'OEE_Ens_NonDurable', 'OEE_Ens_Total': 'OEE_Ens_Total', 'DE_Construction': 'DE_Construction', 'DE_Ensemble': 'DE_Ensemble', });
lyr_contour_ZE_Occitanie_2.set('fieldAliases', {'ID': 'ID', 'NOM_COM': 'NOM_COM', 'NOM_COM_M': 'NOM_COM_M', 'INSEE_COM': 'INSEE_COM', 'STATUT': 'STATUT', 'POPULATION': 'POPULATION', 'INSEE_CAN': 'INSEE_CAN', 'INSEE_ARR': 'INSEE_ARR', 'INSEE_DEP': 'INSEE_DEP', 'INSEE_REG': 'INSEE_REG', 'CODE_EPCI': 'CODE_EPCI', 'LIBGEO': 'LIBGEO', 'ZE2020': 'ZE2020', 'LIBZE2020': 'LIBZE2020', 'ZE2020_PAR': 'ZE2020_PAR', 'DEP': 'DEP', 'REG': 'REG', 'BE2021': 'BE2021', 'LIBBE2021': 'LIBBE2021', 'codeZE20': 'codeZE20', 'pop2019': 'pop2019', 'pop_partRe': 'pop_partRe', 'evol_pop': 'evol_pop', 'pop_15ansp': 'pop_15ansp', 'niveau_vie': 'niveau_vie', 'niveau_v_1': 'niveau_v_1', 'niveau_v_2': 'niveau_v_2', 'taux_pauvr': 'taux_pauvr', 'taux_pau_1': 'taux_pau_1', 'diplôme_p': 'diplôme_p', 'diplôme_B': 'diplôme_B', 'diplôme_C': 'diplôme_C', 'diplôme_1': 'diplôme_1', 'diplôme_E': 'diplôme_E', 'part_0dipl': 'part_0dipl', 'Nb_non_sco': 'Nb_non_sco', 'taux_activ': 'taux_activ', 'taux_act_1': 'taux_act_1', 'taux_choma': 'taux_choma', 'Etab_const': 'Etab_const', 'Etab_TouSe': 'Etab_TouSe', 'creation_e': 'creation_e', 'part_creat': 'part_creat', 'etab_emplo': 'etab_emplo', 'part_effec': 'part_effec', 'pas_transp': 'pas_transp', 'marchePied': 'marchePied', 'velo': 'velo', 'deuxroues': 'deuxroues', 'voiture': 'voiture', 'transports': 'transports', 'taux_indep': 'taux_indep', 'indicateur': 'indicateur', 'nb_emploi_': 'nb_emploi_', 'taux_act_2': 'taux_act_2', 'taux_act_3': 'taux_act_3', 'part_appar': 'part_appar', 'logements': 'logements', 'part_RP': 'part_RP', 'part_RS': 'part_RS', 'part_LV': 'part_LV', 'part_propr': 'part_propr', 'part_maiso': 'part_maiso', 'part_RP_av': 'part_RP_av', 'AUT_Logt20': 'AUT_Logt20', 'COM_Logt20': 'COM_Logt20', 'COM_part_L': 'COM_part_L', 'AUT_part_L': 'AUT_part_L', 'AUT_part_1': 'AUT_part_1', 'COM_part_1': 'COM_part_1', 'OEE_Cons_D': 'OEE_Cons_D', 'OEE_Cons_N': 'OEE_Cons_N', 'OEE_Cons_T': 'OEE_Cons_T', 'OEE_Ens_Du': 'OEE_Ens_Du', 'OEE_Ens_No': 'OEE_Ens_No', 'OEE_Ens_To': 'OEE_Ens_To', 'DE_Constru': 'DE_Constru', 'DE_Ensembl': 'DE_Ensembl', });
lyr_evolution_pop_ZE_3.set('fieldAliases', {'ID': 'ID', 'NOM_COM': 'NOM_COM', 'NOM_COM_M': 'NOM_COM_M', 'INSEE_COM': 'INSEE_COM', 'STATUT': 'STATUT', 'POPULATION': 'POPULATION', 'INSEE_DEP': 'INSEE_DEP', 'INSEE_REG': 'INSEE_REG', 'CODE_EPCI': 'CODE_EPCI', 'ZE2020': 'ZE2020', 'LIBZE2020': 'LIBZE2020', 'pop2019': 'pop2019', 'pop_partRe': 'pop_partRe', 'evol_pop': 'evol_pop', 'pop_15ansp': 'pop_15ansp', 'niveau_vie': 'niveau_vie', 'niveau_v_1': 'niveau_v_1', 'niveau_v_2': 'niveau_v_2', 'taux_pauvr': 'taux_pauvr', 'taux_pau_1': 'taux_pau_1', 'diplôme_p': 'diplôme_p', 'diplôme_B': 'diplôme_B', 'diplôme_C': 'diplôme_C', 'diplôme_1': 'diplôme_1', 'diplôme_E': 'diplôme_E', 'part_0dipl': 'part_0dipl', 'Nb_non_sco': 'Nb_non_sco', 'taux_activ': 'taux_activ', 'taux_act_1': 'taux_act_1', 'taux_choma': 'taux_choma', 'Etab_const': 'Etab_const', 'Etab_TouSe': 'Etab_TouSe', 'creation_e': 'creation_e', 'part_creat': 'part_creat', 'etab_emplo': 'etab_emplo', 'part_effec': 'part_effec', 'pas_transp': 'pas_transp', 'marchePied': 'marchePied', 'velo': 'velo', 'deuxroues': 'deuxroues', 'voiture': 'voiture', 'transports': 'transports', 'taux_indep': 'taux_indep', 'indicateur': 'indicateur', 'nb_emploi_': 'nb_emploi_', 'taux_act_2': 'taux_act_2', 'taux_act_3': 'taux_act_3', 'part_appar': 'part_appar', 'logements': 'logements', 'part_RP': 'part_RP', 'part_RS': 'part_RS', 'part_LV': 'part_LV', 'part_propr': 'part_propr', 'part_maiso': 'part_maiso', 'part_RP_av': 'part_RP_av', 'AUT_Logt20': 'AUT_Logt20', 'COM_Logt20': 'COM_Logt20', 'COM_part_L': 'COM_part_L', 'AUT_part_L': 'AUT_part_L', 'AUT_part_1': 'AUT_part_1', 'COM_part_1': 'COM_part_1', 'OEE_Cons_D': 'OEE_Cons_D', 'OEE_Cons_N': 'OEE_Cons_N', 'OEE_Cons_T': 'OEE_Cons_T', 'OEE_Ens_Du': 'OEE_Ens_Du', 'OEE_Ens_No': 'OEE_Ens_No', 'OEE_Ens_To': 'OEE_Ens_To', 'DE_Constru': 'DE_Constru', 'DE_Ensembl': 'DE_Ensembl', });
lyr_ZE_OCCITANIE_1.set('fieldImages', {'ID': 'TextEdit', 'NOM_COM': 'TextEdit', 'NOM_COM_M': 'TextEdit', 'INSEE_COM': 'TextEdit', 'STATUT': 'TextEdit', 'POPULATION': 'Range', 'INSEE_CAN': 'TextEdit', 'INSEE_ARR': 'TextEdit', 'INSEE_DEP': 'TextEdit', 'INSEE_REG': 'TextEdit', 'CODE_EPCI': 'TextEdit', 'LIBGEO': 'TextEdit', 'ZE2020': 'TextEdit', 'LIBZE2020': 'TextEdit', 'ZE2020_PAR': 'TextEdit', 'DEP': 'TextEdit', 'REG': 'TextEdit', 'BE2021': 'TextEdit', 'LIBBE2021': 'TextEdit', 'codeZE20': 'Range', 'pop2019': 'Range', 'pop_partRegion': 'TextEdit', 'evol_pop': 'TextEdit', 'pop_15ansplus': 'Range', 'niveau_vie_median': 'Range', 'niveau_vie_decile1': 'Range', 'niveau_vie_decile9': 'Range', 'taux_pauvrete': 'TextEdit', 'taux_pauvrete_moins30': 'TextEdit', 'diplôme_pas_peu': 'Range', 'diplôme_BEPC_brevet': 'Range', 'diplôme_CAP_BEP': 'Range', 'diplôme_BAC': 'Range', 'diplôme_EnSup': 'Range', 'part_0diplomes_nonScolarise': 'TextEdit', 'Nb_non_scolarise': 'Range', 'taux_activite_15a24ans': 'TextEdit', 'taux_activite_ensemble': 'TextEdit', 'taux_chomage': 'TextEdit', 'Etab_construction': 'Range', 'Etab_TouSecteur': 'Range', 'creation_ent_TouSecteur': 'Range', 'part_creation_construction': 'TextEdit', 'etab_employeurs': 'Range', 'part_effectif_construction': 'TextEdit', 'pas_transport': 'Range', 'marchePied': 'Range', 'velo': 'Range', 'deuxroues': 'Range', 'voiture': 'Range', 'transportsCommun': 'Range', 'taux_independance': 'Range', 'indicateur_jeunesse': 'Range', 'nb_emploi_LT': 'Range', 'taux_activite_25a54ans': 'TextEdit', 'taux_activite_55a64ans': 'TextEdit', 'part_appartement': 'TextEdit', 'logements': 'Range', 'part_RP': 'TextEdit', 'part_RS': 'TextEdit', 'part_LV': 'TextEdit', 'part_proprio_RS': 'TextEdit', 'part_maisons': 'TextEdit', 'part_RP_av46': 'TextEdit', 'AUT_Logt2020': 'Range', 'COM_Logt2020': 'Range', 'COM_part_LogtIndiv2020': 'TextEdit', 'AUT_part_LogtIndiv2020': 'TextEdit', 'AUT_part_LogtColl2020': 'TextEdit', 'COM_part_LogtColl2020': 'TextEdit', 'OEE_Cons_Durable': 'Range', 'OEE_Cons_NonDurable': 'Range', 'OEE_Cons_Total': 'Range', 'OEE_Ens_Durable': 'Range', 'OEE_Ens_NonDurable': 'Range', 'OEE_Ens_Total': 'Range', 'DE_Construction': 'Range', 'DE_Ensemble': 'Range', });
lyr_contour_ZE_Occitanie_2.set('fieldImages', {'ID': 'TextEdit', 'NOM_COM': 'TextEdit', 'NOM_COM_M': 'TextEdit', 'INSEE_COM': 'TextEdit', 'STATUT': 'TextEdit', 'POPULATION': 'Range', 'INSEE_CAN': 'TextEdit', 'INSEE_ARR': 'TextEdit', 'INSEE_DEP': 'TextEdit', 'INSEE_REG': 'TextEdit', 'CODE_EPCI': 'TextEdit', 'LIBGEO': 'TextEdit', 'ZE2020': 'TextEdit', 'LIBZE2020': 'TextEdit', 'ZE2020_PAR': 'TextEdit', 'DEP': 'TextEdit', 'REG': 'TextEdit', 'BE2021': 'TextEdit', 'LIBBE2021': 'TextEdit', 'codeZE20': 'TextEdit', 'pop2019': 'TextEdit', 'pop_partRe': 'TextEdit', 'evol_pop': 'TextEdit', 'pop_15ansp': 'TextEdit', 'niveau_vie': 'TextEdit', 'niveau_v_1': 'TextEdit', 'niveau_v_2': 'TextEdit', 'taux_pauvr': 'TextEdit', 'taux_pau_1': 'TextEdit', 'diplôme_p': 'TextEdit', 'diplôme_B': 'TextEdit', 'diplôme_C': 'TextEdit', 'diplôme_1': 'TextEdit', 'diplôme_E': 'TextEdit', 'part_0dipl': 'TextEdit', 'Nb_non_sco': 'TextEdit', 'taux_activ': 'TextEdit', 'taux_act_1': 'TextEdit', 'taux_choma': 'TextEdit', 'Etab_const': 'TextEdit', 'Etab_TouSe': 'TextEdit', 'creation_e': 'TextEdit', 'part_creat': 'TextEdit', 'etab_emplo': 'TextEdit', 'part_effec': 'TextEdit', 'pas_transp': 'TextEdit', 'marchePied': 'TextEdit', 'velo': 'TextEdit', 'deuxroues': 'TextEdit', 'voiture': 'TextEdit', 'transports': 'TextEdit', 'taux_indep': 'TextEdit', 'indicateur': 'TextEdit', 'nb_emploi_': 'TextEdit', 'taux_act_2': 'TextEdit', 'taux_act_3': 'TextEdit', 'part_appar': 'TextEdit', 'logements': 'TextEdit', 'part_RP': 'TextEdit', 'part_RS': 'TextEdit', 'part_LV': 'TextEdit', 'part_propr': 'TextEdit', 'part_maiso': 'TextEdit', 'part_RP_av': 'TextEdit', 'AUT_Logt20': 'TextEdit', 'COM_Logt20': 'TextEdit', 'COM_part_L': 'TextEdit', 'AUT_part_L': 'TextEdit', 'AUT_part_1': 'TextEdit', 'COM_part_1': 'TextEdit', 'OEE_Cons_D': 'TextEdit', 'OEE_Cons_N': 'TextEdit', 'OEE_Cons_T': 'TextEdit', 'OEE_Ens_Du': 'TextEdit', 'OEE_Ens_No': 'TextEdit', 'OEE_Ens_To': 'TextEdit', 'DE_Constru': 'TextEdit', 'DE_Ensembl': 'TextEdit', });
lyr_evolution_pop_ZE_3.set('fieldImages', {'ID': 'TextEdit', 'NOM_COM': 'TextEdit', 'NOM_COM_M': 'TextEdit', 'INSEE_COM': 'TextEdit', 'STATUT': 'TextEdit', 'POPULATION': 'Range', 'INSEE_DEP': 'TextEdit', 'INSEE_REG': 'TextEdit', 'CODE_EPCI': 'TextEdit', 'ZE2020': 'TextEdit', 'LIBZE2020': 'TextEdit', 'pop2019': 'TextEdit', 'pop_partRe': 'TextEdit', 'evol_pop': 'TextEdit', 'pop_15ansp': 'TextEdit', 'niveau_vie': 'TextEdit', 'niveau_v_1': 'TextEdit', 'niveau_v_2': 'TextEdit', 'taux_pauvr': 'TextEdit', 'taux_pau_1': 'TextEdit', 'diplôme_p': 'TextEdit', 'diplôme_B': 'TextEdit', 'diplôme_C': 'TextEdit', 'diplôme_1': 'TextEdit', 'diplôme_E': 'TextEdit', 'part_0dipl': 'TextEdit', 'Nb_non_sco': 'TextEdit', 'taux_activ': 'TextEdit', 'taux_act_1': 'TextEdit', 'taux_choma': 'TextEdit', 'Etab_const': 'TextEdit', 'Etab_TouSe': 'TextEdit', 'creation_e': 'TextEdit', 'part_creat': 'TextEdit', 'etab_emplo': 'TextEdit', 'part_effec': 'TextEdit', 'pas_transp': 'TextEdit', 'marchePied': 'TextEdit', 'velo': 'TextEdit', 'deuxroues': 'TextEdit', 'voiture': 'TextEdit', 'transports': 'TextEdit', 'taux_indep': 'TextEdit', 'indicateur': 'TextEdit', 'nb_emploi_': 'TextEdit', 'taux_act_2': 'TextEdit', 'taux_act_3': 'TextEdit', 'part_appar': 'TextEdit', 'logements': 'TextEdit', 'part_RP': 'TextEdit', 'part_RS': 'TextEdit', 'part_LV': 'TextEdit', 'part_propr': 'TextEdit', 'part_maiso': 'TextEdit', 'part_RP_av': 'TextEdit', 'AUT_Logt20': 'TextEdit', 'COM_Logt20': 'TextEdit', 'COM_part_L': 'TextEdit', 'AUT_part_L': 'TextEdit', 'AUT_part_1': 'TextEdit', 'COM_part_1': 'TextEdit', 'OEE_Cons_D': 'TextEdit', 'OEE_Cons_N': 'TextEdit', 'OEE_Cons_T': 'TextEdit', 'OEE_Ens_Du': 'TextEdit', 'OEE_Ens_No': 'TextEdit', 'OEE_Ens_To': 'TextEdit', 'DE_Constru': 'TextEdit', 'DE_Ensembl': 'TextEdit', });
lyr_ZE_OCCITANIE_1.set('fieldLabels', {'ID': 'no label', 'NOM_COM': 'no label', 'NOM_COM_M': 'no label', 'INSEE_COM': 'no label', 'STATUT': 'no label', 'POPULATION': 'no label', 'INSEE_CAN': 'no label', 'INSEE_ARR': 'no label', 'INSEE_DEP': 'no label', 'INSEE_REG': 'no label', 'CODE_EPCI': 'no label', 'LIBGEO': 'no label', 'ZE2020': 'inline label', 'LIBZE2020': 'header label', 'ZE2020_PAR': 'no label', 'DEP': 'no label', 'REG': 'no label', 'BE2021': 'no label', 'LIBBE2021': 'no label', 'codeZE20': 'no label', 'pop2019': 'no label', 'pop_partRegion': 'no label', 'evol_pop': 'no label', 'pop_15ansplus': 'no label', 'niveau_vie_median': 'no label', 'niveau_vie_decile1': 'no label', 'niveau_vie_decile9': 'no label', 'taux_pauvrete': 'no label', 'taux_pauvrete_moins30': 'no label', 'diplôme_pas_peu': 'no label', 'diplôme_BEPC_brevet': 'no label', 'diplôme_CAP_BEP': 'no label', 'diplôme_BAC': 'no label', 'diplôme_EnSup': 'no label', 'part_0diplomes_nonScolarise': 'no label', 'Nb_non_scolarise': 'no label', 'taux_activite_15a24ans': 'no label', 'taux_activite_ensemble': 'no label', 'taux_chomage': 'no label', 'Etab_construction': 'no label', 'Etab_TouSecteur': 'no label', 'creation_ent_TouSecteur': 'no label', 'part_creation_construction': 'no label', 'etab_employeurs': 'no label', 'part_effectif_construction': 'no label', 'pas_transport': 'no label', 'marchePied': 'no label', 'velo': 'no label', 'deuxroues': 'no label', 'voiture': 'no label', 'transportsCommun': 'no label', 'taux_independance': 'no label', 'indicateur_jeunesse': 'no label', 'nb_emploi_LT': 'no label', 'taux_activite_25a54ans': 'no label', 'taux_activite_55a64ans': 'no label', 'part_appartement': 'no label', 'logements': 'no label', 'part_RP': 'no label', 'part_RS': 'no label', 'part_LV': 'no label', 'part_proprio_RS': 'no label', 'part_maisons': 'no label', 'part_RP_av46': 'no label', 'AUT_Logt2020': 'no label', 'COM_Logt2020': 'no label', 'COM_part_LogtIndiv2020': 'no label', 'AUT_part_LogtIndiv2020': 'no label', 'AUT_part_LogtColl2020': 'no label', 'COM_part_LogtColl2020': 'no label', 'OEE_Cons_Durable': 'no label', 'OEE_Cons_NonDurable': 'no label', 'OEE_Cons_Total': 'no label', 'OEE_Ens_Durable': 'no label', 'OEE_Ens_NonDurable': 'no label', 'OEE_Ens_Total': 'no label', 'DE_Construction': 'no label', 'DE_Ensemble': 'no label', });
lyr_contour_ZE_Occitanie_2.set('fieldLabels', {'ID': 'no label', 'NOM_COM': 'no label', 'NOM_COM_M': 'no label', 'INSEE_COM': 'no label', 'STATUT': 'no label', 'POPULATION': 'no label', 'INSEE_CAN': 'no label', 'INSEE_ARR': 'no label', 'INSEE_DEP': 'no label', 'INSEE_REG': 'no label', 'CODE_EPCI': 'no label', 'LIBGEO': 'no label', 'ZE2020': 'no label', 'LIBZE2020': 'no label', 'ZE2020_PAR': 'no label', 'DEP': 'no label', 'REG': 'no label', 'BE2021': 'no label', 'LIBBE2021': 'no label', 'codeZE20': 'no label', 'pop2019': 'no label', 'pop_partRe': 'no label', 'evol_pop': 'no label', 'pop_15ansp': 'no label', 'niveau_vie': 'no label', 'niveau_v_1': 'no label', 'niveau_v_2': 'no label', 'taux_pauvr': 'no label', 'taux_pau_1': 'no label', 'diplôme_p': 'no label', 'diplôme_B': 'no label', 'diplôme_C': 'no label', 'diplôme_1': 'no label', 'diplôme_E': 'no label', 'part_0dipl': 'no label', 'Nb_non_sco': 'no label', 'taux_activ': 'no label', 'taux_act_1': 'no label', 'taux_choma': 'no label', 'Etab_const': 'no label', 'Etab_TouSe': 'no label', 'creation_e': 'no label', 'part_creat': 'no label', 'etab_emplo': 'no label', 'part_effec': 'no label', 'pas_transp': 'no label', 'marchePied': 'no label', 'velo': 'no label', 'deuxroues': 'no label', 'voiture': 'no label', 'transports': 'no label', 'taux_indep': 'no label', 'indicateur': 'no label', 'nb_emploi_': 'no label', 'taux_act_2': 'no label', 'taux_act_3': 'no label', 'part_appar': 'no label', 'logements': 'no label', 'part_RP': 'no label', 'part_RS': 'no label', 'part_LV': 'no label', 'part_propr': 'no label', 'part_maiso': 'no label', 'part_RP_av': 'no label', 'AUT_Logt20': 'no label', 'COM_Logt20': 'no label', 'COM_part_L': 'no label', 'AUT_part_L': 'no label', 'AUT_part_1': 'no label', 'COM_part_1': 'no label', 'OEE_Cons_D': 'no label', 'OEE_Cons_N': 'no label', 'OEE_Cons_T': 'no label', 'OEE_Ens_Du': 'no label', 'OEE_Ens_No': 'no label', 'OEE_Ens_To': 'no label', 'DE_Constru': 'no label', 'DE_Ensembl': 'no label', });
lyr_evolution_pop_ZE_3.set('fieldLabels', {'ID': 'no label', 'NOM_COM': 'no label', 'NOM_COM_M': 'no label', 'INSEE_COM': 'no label', 'STATUT': 'no label', 'POPULATION': 'no label', 'INSEE_DEP': 'no label', 'INSEE_REG': 'no label', 'CODE_EPCI': 'no label', 'ZE2020': 'no label', 'LIBZE2020': 'no label', 'pop2019': 'header label', 'pop_partRe': 'no label', 'evol_pop': 'header label', 'pop_15ansp': 'no label', 'niveau_vie': 'no label', 'niveau_v_1': 'no label', 'niveau_v_2': 'no label', 'taux_pauvr': 'no label', 'taux_pau_1': 'no label', 'diplôme_p': 'no label', 'diplôme_B': 'no label', 'diplôme_C': 'no label', 'diplôme_1': 'no label', 'diplôme_E': 'no label', 'part_0dipl': 'no label', 'Nb_non_sco': 'no label', 'taux_activ': 'no label', 'taux_act_1': 'no label', 'taux_choma': 'no label', 'Etab_const': 'no label', 'Etab_TouSe': 'no label', 'creation_e': 'no label', 'part_creat': 'no label', 'etab_emplo': 'no label', 'part_effec': 'no label', 'pas_transp': 'no label', 'marchePied': 'no label', 'velo': 'no label', 'deuxroues': 'no label', 'voiture': 'no label', 'transports': 'no label', 'taux_indep': 'no label', 'indicateur': 'no label', 'nb_emploi_': 'no label', 'taux_act_2': 'no label', 'taux_act_3': 'no label', 'part_appar': 'no label', 'logements': 'no label', 'part_RP': 'no label', 'part_RS': 'no label', 'part_LV': 'no label', 'part_propr': 'no label', 'part_maiso': 'no label', 'part_RP_av': 'no label', 'AUT_Logt20': 'no label', 'COM_Logt20': 'no label', 'COM_part_L': 'no label', 'AUT_part_L': 'no label', 'AUT_part_1': 'no label', 'COM_part_1': 'no label', 'OEE_Cons_D': 'no label', 'OEE_Cons_N': 'no label', 'OEE_Cons_T': 'no label', 'OEE_Ens_Du': 'no label', 'OEE_Ens_No': 'no label', 'OEE_Ens_To': 'no label', 'DE_Constru': 'no label', 'DE_Ensembl': 'no label', });
lyr_evolution_pop_ZE_3.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});